### ISSUE TITLE
Game ID not found

### ISSUE THREAD

**Issue by yuchenmo** [amazon-research/read-up#1]
Hi, I am following the README file to reproduce your results. The following error occurred when I was evaluating the three modules with the pre-trained model weights. It seems there is no key named 'id' in the annotation file.

```
Traceback (most recent call last):
  File "main.py", line 190, in <module>
    run(args)
  File "main.py", line 135, in run
    solver.load_data()
  File "/.../read-up/solver/self_play_all_vilbert.py", line 83, in load_data
    self.load_dataloader(img_feat_readers, img_feat_readers_gt, tokenizer, splits)
  File "/.../read-up/solver/self_play_all_vilbert.py", line 41, in load_dataloader
    image_features_reader_gt=img_feat_readers_gt[split],
  File "/.../read-up/src/data/self_play_all_vilbert.py", line 41, in __init__
    **kwargs)
  File "/.../read-up/src/data/dataset.py", line 58, in __init__
    self.entries = self._load_dataset()
  File "/.../read-up/src/data/self_play_all_vilbert.py", line 49, in _load_dataset
    game = Game.from_annotation(annotation)
  File "/.../read-up/src/tools/utils.py", line 211, in from_annotation
    game_id=annotation['id'],
KeyError: 'id'
```

I set up the GuessWhat?! dataset following [the instructions here](https://github.com/GuessWhatGame/guesswhat/tree/master). Maybe the dataset has been updated and the code based on the old annotation format is no longer working? If so, will there be an update to accommodate the new dataset format? Thank you for your time in advance!

**Comment by caishuo-C** [comment]
> 



> Hi, I am following the README file to reproduce your results. The following error occurred when I was evaluating the three modules with the pre-trained model weights. It seems there is no key named 'id' in the annotation file.
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 190, in <module>
>     run(args)
>   File "main.py", line 135, in run
>     solver.load_data()
>   File "/.../read-up/solver/self_play_all_vilbert.py", line 83, in load_data
>     self.load_dataloader(img_feat_readers, img_feat_readers_gt, tokenizer, splits)
>   File "/.../read-up/solver/self_play_all_vilbert.py", line 41, in load_dataloader
>     image_features_reader_gt=img_feat_readers_gt[split],
>   File "/.../read-up/src/data/self_play_all_vilbert.py", line 41, in __init__
>     **kwargs)
>   File "/.../read-up/src/data/dataset.py", line 58, in __init__
>     self.entries = self._load_dataset()
>   File "/.../read-up/src/data/self_play_all_vilbert.py", line 49, in _load_dataset
>     game = Game.from_annotation(annotation)
>   File "/.../read-up/src/tools/utils.py", line 211, in from_annotation
>     game_id=annotation['id'],
> KeyError: 'id'
> ```
> 
> I set up the GuessWhat?! dataset following [the instructions here](https://github.com/GuessWhatGame/guesswhat/tree/master). Maybe the dataset has been updated and the code based on the old annotation format is no longer working? If so, will there be an update to accommodate the new dataset format? Thank you for your time in advance!



> Hi, I am following the README file to reproduce your results. The following error occurred when I was evaluating the three modules with the pre-trained model weights. It seems there is no key named 'id' in the annotation file.
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 190, in <module>
>     run(args)
>   File "main.py", line 135, in run
>     solver.load_data()
>   File "/.../read-up/solver/self_play_all_vilbert.py", line 83, in load_data
>     self.load_dataloader(img_feat_readers, img_feat_readers_gt, tokenizer, splits)
>   File "/.../read-up/solver/self_play_all_vilbert.py", line 41, in load_dataloader
>     image_features_reader_gt=img_feat_readers_gt[split],
>   File "/.../read-up/src/data/self_play_all_vilbert.py", line 41, in __init__
>     **kwargs)
>   File "/.../read-up/src/data/dataset.py", line 58, in __init__
>     self.entries = self._load_dataset()
>   File "/.../read-up/src/data/self_play_all_vilbert.py", line 49, in _load_dataset
>     game = Game.from_annotation(annotation)
>   File "/.../read-up/src/tools/utils.py", line 211, in from_annotation
>     game_id=annotation['id'],
> KeyError: 'id'
> ```
> 
> I set up the GuessWhat?! dataset following [the instructions here](https://github.com/GuessWhatGame/guesswhat/tree/master). Maybe the dataset has been updated and the code based on the old annotation format is no longer working? If so, will there be an update to accommodate the new dataset format? Thank you for your time in advance!

same issue +1

**Comment by caishuo-C** [comment]
> Hi, I am following the README file to reproduce your results. The following error occurred when I was evaluating the three modules with the pre-trained model weights. It seems there is no key named 'id' in the annotation file.
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 190, in <module>
>     run(args)
>   File "main.py", line 135, in run
>     solver.load_data()
>   File "/.../read-up/solver/self_play_all_vilbert.py", line 83, in load_data
>     self.load_dataloader(img_feat_readers, img_feat_readers_gt, tokenizer, splits)
>   File "/.../read-up/solver/self_play_all_vilbert.py", line 41, in load_dataloader
>     image_features_reader_gt=img_feat_readers_gt[split],
>   File "/.../read-up/src/data/self_play_all_vilbert.py", line 41, in __init__
>     **kwargs)
>   File "/.../read-up/src/data/dataset.py", line 58, in __init__
>     self.entries = self._load_dataset()
>   File "/.../read-up/src/data/self_play_all_vilbert.py", line 49, in _load_dataset
>     game = Game.from_annotation(annotation)
>   File "/.../read-up/src/tools/utils.py", line 211, in from_annotation
>     game_id=annotation['id'],
> KeyError: 'id'
> ```
> 
> I set up the GuessWhat?! dataset following [the instructions here](https://github.com/GuessWhatGame/guesswhat/tree/master). Maybe the dataset has been updated and the code based on the old annotation format is no longer working? If so, will there be an update to accommodate the new dataset format? Thank you for your time in advance!

same issue+1
